In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

plt.style.use('default')

pd.set_option('display.max_columns', None)

In [2]:
fund_master = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\fund_master_clean.csv")

nav_history = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\nav_history_clean.csv")

aum = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\aum_by_fund_house_clean.csv")

sip = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\monthly_sip_inflows_clean.csv")

category = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\category_inflows_clean.csv")

folio = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\industry_folio_count_clean.csv")

performance = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\scheme_performance_clean.csv")

investor_transactions = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\investor_transactions_clean.csv")

portfolio = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\portfolio_holdings_clean.csv")

benchmark = pd.read_csv("D:\\BlueStock FineTech\\data\\processed\\benchmark_indices_clean.csv")

# Section A
# Daily Returns Calculation & Validation

In [3]:
# Create Daily Data
# Sort data

nav_history = nav_history.sort_values(
    ['amfi_code','date']
)

# Daily return calculation

nav_history['daily_return'] = (
    nav_history
    .groupby('amfi_code')['nav']
    .pct_change()
)

nav_history.head()

   amfi_code        date       nav  daily_return
0     100016  2022-01-03  520.4608           NaN
1     100016  2022-01-04  515.0971     -0.010306
2     100016  2022-01-05  521.7239      0.012865
3     100016  2022-01-06  515.7880     -0.011377
4     100016  2022-01-07  515.1639     -0.001210

In [8]:
daily_return_summary = (
    nav_history
    .groupby('amfi_code')['daily_return']
    .agg(
        mean_return='mean',
        volatility='std',
        min_return='min',
        max_return='max'
    )
    .reset_index()
)

daily_return_summary.head()

   amfi_code  mean_return  volatility  min_return  max_return
0     100016     0.000142    0.009164   -0.024744    0.032145
1     100025     0.000170    0.002460   -0.008188    0.008837
2     100033     0.001080    0.011929   -0.044238    0.041954
3     101206     0.000852    0.009177   -0.038121    0.033956
4     101207     0.000424    0.016251   -0.051847    0.054851

In [4]:
# Validation
nav_history['daily_return'].describe()

count    45960.000000
mean         0.000631
std          0.010290
min         -0.058102
25%         -0.005042
50%          0.000340
75%          0.006324
max          0.064713
Name: daily_return, dtype: float64

In [5]:
nav_history['daily_return'].isnull().sum()

np.int64(40)

In [9]:
print("Missing Returns:", nav_history['daily_return'].isnull().sum())

daily_return_summary.head()

Missing Returns: 40

   amfi_code  mean_return  volatility  min_return  max_return
0     100016     0.000142    0.009164   -0.024744    0.032145
1     100025     0.000170    0.002460   -0.008188    0.008837
2     100033     0.001080    0.011929   -0.044238    0.041954
3     101206     0.000852    0.009177   -0.038121    0.033956
4     101207     0.000424    0.016251   -0.051847    0.054851

In [10]:
daily_return_summary.to_csv(
    r"D:\BlueStock FineTech\data\processed\daily_return_summary.csv",
    index=False
)